version: "3.8"
services:
  db:
    image: postgres:15-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=db
    ports:
      - 5432:5432

  app:
    build:
      context: ./
      dockerfile: Dockerfile
    restart: unless-stopped
    command: ${COMMAND:-npm run dev}
    volumes:
      - ./:/src
      - /src/node_modules
      - /src/.next
    working_dir: /src
    ports:
      - "3000:3000"
